version: '3.6'
services:
  postgres:
    image: postgres:13
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: 1000jours
      POSTGRES_USER: 1000jours
      POSTGRES_PASSWORD: milleetunjoursdebebe

  strapi:
    build: strapi
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: 1000jours
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: 1000jours
      DATABASE_PASSWORD: milleetunjoursdebebe
      JWT_SECRET: jwtsupersecretachanger
      ADMIN_JWT_SECRET: jwtadminachangeraussi
    restart: always
    volumes:
      - ./strapi:/srv/app
    ports:
      - '1337:1337'
    depends_on:
      - postgres

  graphql-engine:
    build: hasura
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    volumes:
      - ./hasura/migrations:/hasura-migrations
      - ./hasura/metadata:/hasura-metadata
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://1000jours:milleetunjoursdebebe@postgres:5432/1000jours
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: hasurac'estpasmal
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "anonymous"
      HASURA_ACTION_BASE_URL: http://localhost:1337

volumes:
  db_data:
