name: ğŸ‘“ Review Auto
on:
  push:
    branches:
      - "feat-**"
      - "fix-**"
      - "feat/**"
      - "fix/**"
      - "develop"

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.ref }}

jobs:
  register:
    name: Build & Register Strapi
    runs-on: ubuntu-latest
    steps:
      - name: Use autodevops build and register
        uses: SocialGouv/actions/autodevops-build-register@v1
        with:
          environment: dev
          dockercontext: ./back/strapi
          imageName: 1000jours/strapi
          token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: ./back/strapi/Dockerfile

  kontinuous:
    name: "Deploy on Kubernetes ğŸ³"
    needs: [register]
    uses: socialgouv/workflows/.github/workflows/use-ks-gh-review-auto.yaml@master
    secrets: inherit
